-- Cân kiểm kho: one photographed weighing, independent from the two-step slip.
-- The Edge Function is the only writer; anon may read for the operator UI.

create table if not exists public.can_kiem_kho (
  id bigint generated by default as identity primary key,
  event_id uuid not null unique,
  ma_san_pham text not null check (char_length(ma_san_pham) between 1 and 512),
  khoi_luong numeric(14,3) not null check (khoi_luong >= 0),
  khoi_luong_loi numeric(14,3) not null default 0 check (khoi_luong_loi >= 0),
  khoi_luong_bi numeric(14,3) not null default 0 check (khoi_luong_bi >= 0),
  don_vi text not null default 'kg' check (don_vi in ('kg', 'g', 'lb')),
  captured_at timestamptz not null default now(),
  image_path text not null,
  image_url text,
  image_public_id text,
  gateway_id text,
  station_id text,
  camera_id text,
  analysis_id text,
  frame_sha256 text check (
    frame_sha256 is null or frame_sha256 ~* '^[0-9a-f]{64}$'
  ),
  payload_hash text check (
    payload_hash is null or payload_hash ~* '^[0-9a-f]{64}$'
  ),
  weight_source text not null default 'manual',
  qr_source text not null default 'unknown',
  status text not null default 'confirmed' check (status in ('confirmed', 'void')),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

comment on table public.can_kiem_kho is
  'Cân kiểm kho: một ảnh, một lần đọc khối lượng; không có bước chụp cân lõi riêng.';
comment on column public.can_kiem_kho.ma_san_pham is 'Mã sản phẩm / nội dung QR.';
comment on column public.can_kiem_kho.khoi_luong is 'Khối lượng đọc từ ảnh cân duy nhất.';
comment on column public.can_kiem_kho.khoi_luong_loi is
  'Khối lượng lõi nhập kèm; không phát sinh ảnh cân lõi riêng.';
comment on column public.can_kiem_kho.khoi_luong_bi is 'Khối lượng bì nhập kèm.';

create index if not exists can_kiem_kho_ma_san_pham_idx
  on public.can_kiem_kho (ma_san_pham);
create index if not exists can_kiem_kho_captured_at_idx
  on public.can_kiem_kho (captured_at desc);
create index if not exists can_kiem_kho_station_time_idx
  on public.can_kiem_kho (gateway_id, station_id, camera_id, captured_at desc);
create index if not exists can_kiem_kho_analysis_id_idx
  on public.can_kiem_kho (analysis_id)
  where analysis_id is not null;

alter table public.can_kiem_kho enable row level security;
revoke all on table public.can_kiem_kho from anon, authenticated;
grant select on table public.can_kiem_kho to anon;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'can_kiem_kho'
      and policyname = 'anon_read_can_kiem_kho'
  ) then
    create policy anon_read_can_kiem_kho
      on public.can_kiem_kho
      for select
      to anon
      using (true);
  end if;
end
$$;
