-- Production schema for the QR + scale ingestion service.
create extension if not exists pgcrypto;

create table if not exists public.devices (
  id text primary key,
  name text,
  active boolean not null default true,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now()
);

create table if not exists public.rolls (
  qr_code text primary key,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb
);

create table if not exists public.measurements (
  id bigint generated by default as identity primary key,
  event_id uuid not null unique,
  qr_code text not null,
  weight numeric(14,3) not null check (weight >= 0),
  tare_weight numeric(14,3) not null default 0 check (tare_weight >= 0 and tare_weight <= weight),
  net_weight numeric(14,3) generated always as (weight - tare_weight) stored,
  unit text not null check (unit in ('kg', 'g', 'lb')),
  captured_at timestamptz not null default now(),
  image_path text not null,
  image_url text,
  image_public_id text,
  device_id text references public.devices(id),
  weight_source text not null default 'manual',
  qr_source text not null default 'unknown',
  weight_kind text not null default 'gross',
  status text not null default 'confirmed' check (status in ('confirmed', 'void')),
  confirmed_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

-- Upgrade the earlier prototype schema without destroying existing records.
alter table public.measurements
  add column if not exists device_id text references public.devices(id),
  add column if not exists tare_weight numeric(14,3) not null default 0,
  add column if not exists net_weight numeric(14,3) generated always as (weight - tare_weight) stored,
  add column if not exists image_url text,
  add column if not exists image_public_id text,
  add column if not exists weight_source text not null default 'manual',
  add column if not exists qr_source text not null default 'unknown',
  add column if not exists weight_kind text not null default 'gross',
  add column if not exists status text not null default 'confirmed',
  add column if not exists confirmed_at timestamptz not null default now(),
  add column if not exists metadata jsonb not null default '{}'::jsonb,
  add column if not exists created_at timestamptz not null default now();

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.measurements'::regclass
      and conname = 'measurements_tare_weight_check'
  ) then
    alter table public.measurements
      add constraint measurements_tare_weight_check
      check (tare_weight >= 0 and tare_weight <= weight);
  end if;
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.measurements'::regclass
      and conname = 'measurements_status_check'
  ) then
    alter table public.measurements
      add constraint measurements_status_check
      check (status in ('confirmed', 'void'));
  end if;
end $$;

create index if not exists measurements_qr_idx
  on public.measurements (qr_code);

create index if not exists measurements_captured_at_idx
  on public.measurements (captured_at desc);

create index if not exists measurements_device_idx
  on public.measurements (device_id, captured_at desc);

create index if not exists measurements_lookup_idx
  on public.measurements (qr_code, status, captured_at desc);

alter table public.devices enable row level security;
alter table public.rolls enable row level security;
alter table public.measurements enable row level security;

-- No anon/authenticated policies are created. Only the Edge Function's
-- service-role client can access these tables.
revoke all on table public.devices from anon, authenticated;
revoke all on table public.rolls from anon, authenticated;
revoke all on table public.measurements from anon, authenticated;

insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'roll-captures',
  'roll-captures',
  false,
  6291456,
  array['image/jpeg']
)
on conflict (id) do update
set public = false,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;
