-- Production table for automatic scale captures.
-- Binary image data stays in Cloudinary; this table stores only its URL/public ID.
create table if not exists public.can_tu_dong (
  id bigint generated by default as identity primary key,
  event_id uuid not null unique,
  qr_code text not null,
  weight numeric(14,3) not null check (weight >= 0),
  tare_weight numeric(14,3) not null default 0
    check (tare_weight >= 0 and tare_weight <= weight),
  net_weight numeric(14,3) generated always as (weight - tare_weight) stored,
  unit text not null check (unit in ('kg', 'g', 'lb')),
  captured_at timestamptz not null default now(),
  image_path text not null,
  image_url text,
  image_public_id text,
  device_id text references public.devices(id),
  weight_source text not null default 'manual',
  qr_source text not null default 'unknown',
  weight_kind text not null default 'gross',
  status text not null default 'confirmed' check (status in ('confirmed', 'void')),
  confirmed_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

comment on table public.can_tu_dong is
  'Automatic scale records. Captured images are stored in Cloudinary.';
comment on column public.can_tu_dong.image_path is
  'Cloudinary public ID; legacy rows may contain a Supabase Storage path.';
comment on column public.can_tu_dong.image_url is
  'Cloudinary secure delivery URL.';

create index if not exists can_tu_dong_qr_idx
  on public.can_tu_dong (qr_code);
create index if not exists can_tu_dong_captured_at_idx
  on public.can_tu_dong (captured_at desc);
create index if not exists can_tu_dong_device_idx
  on public.can_tu_dong (device_id, captured_at desc);
create index if not exists can_tu_dong_lookup_idx
  on public.can_tu_dong (qr_code, status, captured_at desc);
create index if not exists can_tu_dong_image_public_id_idx
  on public.can_tu_dong (image_public_id)
  where image_public_id is not null;

alter table public.can_tu_dong enable row level security;
revoke all on table public.can_tu_dong from anon, authenticated;

-- Keep existing production history available after switching the Edge Functions.
insert into public.can_tu_dong (
  id,
  event_id,
  qr_code,
  weight,
  tare_weight,
  unit,
  captured_at,
  image_path,
  image_url,
  image_public_id,
  device_id,
  weight_source,
  qr_source,
  weight_kind,
  status,
  confirmed_at,
  metadata,
  created_at
)
overriding system value
select
  id,
  event_id,
  qr_code,
  weight,
  tare_weight,
  unit,
  captured_at,
  image_path,
  image_url,
  image_public_id,
  device_id,
  weight_source,
  qr_source,
  weight_kind,
  status,
  confirmed_at,
  metadata,
  created_at
from public.measurements
on conflict (event_id) do nothing;

select setval(
  pg_get_serial_sequence('public.can_tu_dong', 'id'),
  coalesce((select max(id) from public.can_tu_dong), 1),
  exists(select 1 from public.can_tu_dong)
);
